import{a as E,S as q,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",$="47040317-0d9018ce78b59a4267667365b",B=15;async function p(t,o=1){const s={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:B};try{return(await E.get(R,{params:s})).data}catch(n){throw console.error("Error fetching images:",n),n}}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more");let M=new q(".gallery a",{captionsData:"alt",captionsDelay:250});function y(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,views:c,comments:P,downloads:v})=>`
      <li class="gallery-item">
        <a href="${n}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><span>${r}</span>Likes</p>
          <p><span>${c}</span>Views</p>
          <p><span>${P}</span>Comments</p>
          <p><span>${v}</span>Downloads</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",o),M.refresh()}function x(){h.innerHTML=""}function L(){f.classList.remove("hidden")}function w(){f.classList.add("hidden")}function b(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}const m=document.querySelector(".form"),A=m.querySelector('input[name="search-text"]'),I=document.querySelector(".load-more");let d="",i=1,u=0;const S=15;l();m.addEventListener("submit",O);I.addEventListener("click",_);async function O(t){t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){a.warning({message:"Please enter a search term!",position:"topRight"});return}d=o,i=1,x(),l(),L();try{const s=await p(d,i);if(s.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}u=s.totalHits,y(s.hits),a.success({message:`Found ${u} images.`,position:"topRight"}),u>i*S?b():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){a.error({message:"Error fetching images. Please try again later.",position:"topRight"}),console.error(s)}finally{w(),m.reset(),A.focus()}}async function _(){i+=1,L(),l();try{const t=await p(d,i);y(t.hits),H(),i*S>=u?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):b()}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{w()}}function H(){const t=document.querySelector(".gallery-item");if(!t)return;const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
