import{a as P,S as E,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const R="https://pixabay.com/api/",$="47040317-0d9018ce78b59a4267667365b";function h(o){const r={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"};return P.get(R,{params:r}).then(t=>t.data).catch(t=>{throw console.error("Error fetching images:",t),t})}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more");let B=new E(".gallery a",{captionsData:"alt",captionsDelay:250});function y(o){const r=o.map(({webformatURL:t,largeImageURL:l,tags:e,likes:s,views:a,comments:v,downloads:q})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${t}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><span>${s}</span>Likes</p>
          <p><span>${a}</span>Views</p>
          <p><span>${v}</span>Comments</p>
          <p><span>${q}</span>Downloads</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){p.innerHTML=""}function L(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function w(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const m=document.querySelector(".form"),x=m.querySelector('input[name="search-text"]'),I=document.querySelector(".load-more");let d="",i=1,u=0;const S=15;c();m.addEventListener("submit",O);I.addEventListener("click",A);async function O(o){o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!",position:"topRight"});return}d=r,i=1,M(),c(),L();try{const t=await h(d,i);if(t.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}u=t.totalHits,y(t.hits),n.success({message:`Found ${u} images.`,position:"topRight"}),u>i*S?w():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.error({message:"Error fetching images. Please try again later.",position:"topRight"}),console.error(t)}finally{b(),m.reset(),x.focus()}}async function A(){i+=1,L(),c();try{const o=await h(d,i);y(o.hits),H(),i*S>=u?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):w()}catch{n.error({message:"Error loading more images.",position:"topRight"})}finally{b()}}function H(){const o=document.querySelector(".gallery-item");if(!o)return;const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
