import{a as P,S as q,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const E="https://pixabay.com/api/",R="47040317-0d9018ce78b59a4267667365b";function h(o){const r={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"};return P.get(E,{params:r}).then(t=>t.data).catch(t=>{throw console.error("Error fetching images:",t),t})}const p=document.querySelector(".gallery"),f=document.querySelector(".loader");let B=new q(".gallery a",{captionsData:"alt",captionsDelay:250});function g(o){const r=o.map(({webformatURL:t,largeImageURL:l,tags:e,likes:s,views:a,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${l}">
          <img src="${t}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><span>${s}</span>Likes</p>
          <p><span>${a}</span>Views</p>
          <p><span>${S}</span>Comments</p>
          <p><span>${v}</span>Downloads</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),B.refresh()}function M(){p.innerHTML=""}function y(){f.classList.remove("hidden")}function L(){f.classList.add("hidden")}function b(){loadMoreBtn.classList.remove("hidden")}function c(){loadMoreBtn.classList.add("hidden")}const m=document.querySelector(".form"),$=m.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let d="",i=1,u=0;const w=15;c();m.addEventListener("submit",I);x.addEventListener("click",O);async function I(o){o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!",position:"topRight"});return}d=r,i=1,M(),c(),y();try{const t=await h(d,i);if(t.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}u=t.totalHits,g(t.hits),n.success({message:`Found ${u} images.`,position:"topRight"}),u>i*w?b():(c(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){n.error({message:"Error fetching images. Please try again later.",position:"topRight"}),console.error(t)}finally{L(),m.reset(),$.focus()}}async function O(){i+=1,y(),c();try{const o=await h(d,i);g(o.hits),A(),i*w>=u?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):b()}catch{n.error({message:"Error loading more images.",position:"topRight"})}finally{L()}}function A(){const o=document.querySelector(".gallery-item");if(!o)return;const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
